config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'reports/index'
  get 'marks/index'

  resources :employees
  resources :marks
  resources :reports, only: [:index]

  get 'dashboards/index'
  root 'dashboards#index'

  get 'reports/employees/:employee_id' => 'reports#show', :as => 'report_employees'

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :marks
      resources :fingerprints
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :employee_schedules
  has_many :schedules, :through => :employee_schedules
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    return redirect_to root_path if !current_user.has_role?(:admin)
    @employees = Employee.all
  end

  def new
    return redirect_to root_path if !current_user.has_role?(:admin)
    @employee = Employee.new
  end

  def create
    return redirect_to root_path if !current_user.has_role?(:admin)
    Employee.transaction do
      @employee = Employee.create employee_params
      flash[:success] = "Se ha creado exitosamente."
      @schedule = Schedule.last
      @employee_schedule = EmployeeSchedule.create employee_id: @employee.id, schedule_id: @schedule.id
      redirect_to employees_path
    end
  end

  def edit
    return redirect_to root_path if !current_user.has_role?(:admin)
    @employee = Employee.find(params[:id])
  end

  def update
    return redirect_to root_path if !current_user.has_role?(:admin)
    Employee.transaction do
      @employee = Employee.find(params[:id])
      @employee.update_attributes employee_params
      flash[:success] = "Se ha actualizado exitosamente."
      redirect_to employees_path
    end
  end


  def employee_params
    params.require(:employee).permit(
      :names,
      :last_name,
      :mother_last_name,
      :phone,
      :rut,
      :email
    )
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_data_form.slim
hr
  h4 
    strong Datos personales
hr
#userData
  .form-row
    .form-group.col-md-6
      h4 for="InputName"  Rut
      = employee.text_field :rut, {class: "form-control", id: "inputRut", placeholder: "Ingrese su rut", required: true}
    .form-group.col-md-6
      h4 for="InputName"  Nombres
      = employee.text_field :names, {class: "form-control", id: "inputName", placeholder: "Ingrese su(s) nombre(s)", required: true}
  .form-row
    .form-group.col-md-6
      h4 for="InputLastName" Apellido Paterno
      = employee.text_field :last_name, {class: "form-control", id: "inputLastName", placeholder:"Ingrese su apellido paterno", required: true}
    .form-group.col-md-6
      h4 for="InputLastName" Apellido Materno
      = employee.text_field :mother_last_name, {class: "form-control", id: "inputLastName", placeholder:"Ingrese su apellido materno", required: true}
  .form-row
    .form-group.col-md-6.has-danger
      h4 for="InputEmail1"  Correo electrónico
      = employee.email_field :email, {class: "form-control", id: "inputEmail1", placeholder:"email@ejemplo.com", required: true}
    .form-group.col-md-6
      h4 for="InputPhone"  Teléfono
      = employee.text_field :phone, {class: "form-control", id: "inputPhone", placeholder: "+569 9999 5555", required: true}
  .form-row
    = submit_tag("Enviar", id: "buttonSubmit", class: "btn btn-dark") 

app/views/employees/edit.slim
.pl-3
  = form_for @employee, url:  employee_path, html: {method: 'put',id: "formEmployee", autocomplete: "off"} do |employee|  
    .row
      #contact_form.col-12.col-md-12
        h2 
          = link_to employees_path do
            = icon('fas', 'arrow-left') 
          |  Edición de trabajador
        = render partial: 'data_form', locals: { employee: employee }

app/views/employees/index.slim
.row.content
  .col-md-12  
    hr
    h2.pl-3 
      | Trabajadores 
      = link_to new_employee_path do
        = icon('fas', 'plus')
    hr

.row
  .col-md-12.mt-3
    #content.tab-content
      #sent.tab-pane.fade.show.active role="tabpanel"
        div.container-fluid.mb-4
          table.table.responsive.table-striped.table-bordered.sentTable cellspacing="0" width="100%"
            thead.thead-dark
              tr
                th Nombres
                th Apellido Paterno
                th Apellido Materno
                th Rut
                th Correo
                th Teléfono
                th Opciones
            tbody[style='text-transform: capitalize']
              - @employees.each do |e|
                tr
                  td= e.names 
                  td= e.last_name
                  td= e.mother_last_name
                  td= e.rut
                  td= e.email
                  td= e.phone
                  td.text-center 
                    =link_to edit_employee_path(e.id), {class: 'btn btn-danger'} do
                      = icon('fas', 'edit')                  
                    button.btn.btn-warning style="text-color:#fff;"
                      = icon('fas', 'clock')

app/views/employees/new.slim
.pl-3
  = form_for @employee, url:  employees_path, html: {id: "formEmployee", autocomplete: "off"} do |employee|  
    .row
      #contact_form.col-12.col-md-12
          = render partial: 'data_form', locals: { employee: employee }