config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'reports/index'
  get 'marks/index'

  resources :employees
  resources :marks
  resources :reports, only: [:index]

  get 'dashboards/index'
  root 'dashboards#index'

  get 'reports/employees/:employee_id' => 'reports#show', :as => 'report_employees'

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :marks
      resources :fingerprints
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    return redirect_to root_path if !current_user.has_role?(:admin)
    @employees  = Employee.all
  end

  def show
    return redirect_to root_path if !current_user.has_role?(:admin)
    @summary    = {}
    @employee   = Employee.find(params[:employee_id])
    @start_date = params[:start_date] || Date.today.at_beginning_of_month 
    @end_date   = params[:end_date] || @start_date.end_of_month

    (@start_date.to_date..@end_date.to_date).each do |day|
      @marks    = Mark.includes(:employee_schedule).by_day(@employee, day)
      if !@marks.blank?
        @summary[:"#{day}"] = daily_summary @marks, day
      else
        @summary[:"#{day}"] = {}
      end
    end
  end

  def daily_summary(marks, day)
    daily_summary = {}
    daily_summary[:color] = '#ED2939'
    marks.each do |mark|
      case mark.type_mark_id 
      when 1    
        #entrada
        daily_summary[:color] = color_aasm mark.aasm_state 
        daily_summary[:time_in] = mark.date_time_mark.strftime("%H:%M:%S")
      when 2    
        #salida colacion
        daily_summary[:time_out_collation] = mark.date_time_mark.strftime("%H:%M:%S")
      when 3
        #entrada colacion
        daily_summary[:time_in_collation] = mark.date_time_mark.strftime("%H:%M:%S")
      when 4
        #salida
        daily_summary[:time_out] = mark.date_time_mark.strftime("%H:%M:%S")
      end
    end
    daily_summary[:collation_time] = calculate_collation daily_summary
    daily_summary[:work_time] = calculate_work daily_summary
    daily_summary[:no_work_time] = calculate_no_work daily_summary, day, marks[0].employee_schedule_id
    daily_summary
  end

  def calculate_collation daily_summary
    return '' unless daily_summary.has_key?(:time_in_collation) 
    return '' unless daily_summary.has_key?(:time_out_collation)
    return time_diff(daily_summary[:time_in_collation].to_time, daily_summary[:time_out_collation].to_time)
  end

  def calculate_work daily_summary
    return '' unless daily_summary.has_key?(:time_in) 
    return '' unless daily_summary.has_key?(:time_out)
    return '' if daily_summary[:collation_time] == ''
    return '' unless daily_summary.has_key?(:collation_time)
    work_withouth_collation = time_diff(daily_summary[:time_out].to_time, daily_summary[:time_in].to_time)
    collation_time = Time.parse(daily_summary[:collation_time])
    collation_time_seconds = collation_time.hour * 60 * 60 + collation_time.min * 60 + collation_time.sec

    return (work_withouth_collation.to_time - collation_time_seconds.seconds).strftime("%H:%M:%S")
  end

  def time_diff start_time, end_time
    seconds_diff = (start_time - end_time).to_i.abs

    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600

    minutes = seconds_diff / 60
    seconds_diff -= minutes * 60

    seconds = seconds_diff

    "#{hours.to_s.rjust(2, '0')}:#{minutes.to_s.rjust(2, '0')}:#{seconds.to_s.rjust(2, '0')}"
  end

  def calculate_no_work daily_summary, day, schedule
    return '' if daily_summary[:work_time] == ''
    @day_c = day.strftime("%A")
    @schedule = EmployeeSchedule.find(schedule)
    @detail_day = DetailSchedule.where(schedule_id: @schedule.schedule_id, day: @day_c).first!
    diff = time_diff @detail_day.work_time.to_time, daily_summary[:work_time].to_time
    if daily_summary[:work_time] >= @detail_day.work_time
      return '00:00:00'
    else
      return diff
    end
  end

  def color_aasm aasm_state
    case aasm_state
    when 'correct'
      return ''
    when 'delayed'
      return '#ffc107'
    when 'out'
      return 'ED2939'
    when 'away'
      return '#6c757d'
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.slim
.row.content
  .col-md-12  
    hr
    h2.pl-3 
      | Trabajadores 
    hr

.row
  .col-md-12.mt-3
    #content.tab-content
      #sent.tab-pane.fade.show.active role="tabpanel"
        div.container-fluid.mb-4
          table.table.responsive.table-striped.table-bordered.sentTable cellspacing="0" width="100%"
            thead.thead-dark
              tr
                th Nombres
                th Apellido Paterno
                th Apellido Materno
                th Rut
                th Reporte
            tbody[style='text-transform: capitalize']
              - @employees.each do |e|
                tr
                  td= e.names 
                  td= e.last_name
                  td= e.mother_last_name
                  td= e.rut
                  td.text-center 
                    =link_to report_employees_path(e.id), {class: 'btn btn-danger'} do
                      = icon('fas', 'file-alt')                  
                    

app/views/reports/show.html.slim
.row.content
  .col-md-12  
    hr
    h2.pl-3 
      | Reporte mensual: 
      | #{@employee.names} #{@employee.last_name} #{@employee.mother_last_name}
    hr

= form_tag({controller: "reports", action: "show"}, method: "get", id:"searchForm") do
  .row.pl-3
    .col-md-3.align-self-end
      .form-group
        label Fecha Inicio
        input.form-control#start_date type="date" name="start_date" value="#{Date.today.at_beginning_of_month}" required="required"
    .col-md-3.align-self-end
      .form-group
        label Fecha Final
        input.form-control#end_date type="date" name="end_date" value="#{Date.today.at_end_of_month}" required="required"
        input type="hidden" name="employee_id" value="#{@employee.id}"
    .col-md-3.align-self-end
      .form-group
        button.btn.btn-primary.search Buscar 
    .col-md-3.align-self-end
      .row
        fieldset
          = icon('fas', 'square', style:'background-color: #000;color:#ffc107;') 
          label  Atrasada
      .row
        fieldset
          = icon('fas', 'square', style:'background-color: #000;color:#ED2939;') 
          label  Ausente
      .row
        fieldset
          = icon('fas', 'square', style:'background-color: #000; color:#6c757d;') 
          label  Fuera de lugar
hr

.row
  .col-md-12.mt-3
    #content.tab-content
      #sent.tab-pane.fade.show.active role="tabpanel"
        div.container-fluid.mb-4
          table.table.responsive.table-striped.table-bordered.reportTable cellspacing="0" width="100%"
            thead.thead-dark 
              tr
                th Fecha
                th Hora entrada
                th Hora salida a colación
                th Hora entrada a colación
                th Hora salida
                th Tiempo colación
                th Tiempo trabajado
                th Tiempo no trabajado

            tbody[style='text-transform: capitalize']
              - @summary.each do |day|
                tr style="background-color:#{day.second[:color]}"
                  td= day.first
                  td= day.second[:time_in]
                  td= day.second[:time_out_collation]
                  td= day.second[:time_in_collation]
                  td= day.second[:time_out]
                  td= day.second[:collation_time]
                  td= day.second[:work_time]
                  td= day.second[:no_work_time] 