config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'reports/index'
  get 'marks/index'

  resources :employees
  resources :marks
  resources :reports, only: [:index]

  get 'dashboards/index'
  root 'dashboards#index'

  get 'reports/employees/:employee_id' => 'reports#show', :as => 'report_employees'

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :marks
      resources :fingerprints
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Lindi
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body 
    .wrapper
      nav#sidebar
        /! Sidebar Header
        .sidebar-header
          h3.text-center
            = image_tag('logo-unab.png', width: '130px')
          strong
            = icon('fas','bars')
        /! Sidebar Links
        ul.list-unstyled.components
          - if current_user.has_role?(:admin)
            li.active
              a data-toggle="collapse" 
                = link_to employees_path do
                  = icon('fas','users')
                  | Trabajador  
          li.active
            a data-toggle="collapse" 
              = link_to marks_path do
                = icon('fas','flag-checkered')
                |  Marcación 
          - if current_user.has_role?(:admin)
            li.active
              a data-toggle="collapse" 
                = link_to reports_path do
                  = icon('fas','clipboard-list')
                  |   Reporteria
      #content
          nav.navbar.navbar-expand-md.navbar-dark.bg-dark.flex-row
            a.navbar-brand.mr-auto href="/" 
              button#sidebarCollapse.btn.btn-info.navbar-btn type="button" 
                i.glyphicon.glyphicon-align-left
                span = icon('fas','bars')
            ul.navbar-nav.flex-row.mr-lg-0
              li.nav-item.dropdown
                a#navbarDropdownMenuLink.nav-link.dropdown-toggle.mr-3.mr-lg-0 aria-haspopup="true" data-toggle="dropdown" 
                  i.fa.fa-user
                  span.caret
                .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdownMenuLink" 
                  a.dropdown-item href=""  Perfil
                  = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
                    | Salir
                    
            
          .container
            - flash.each do |key, value| 
              div class="alert alert-#{key}" role="alert" = value
            = yield

app/views/layouts/devise.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Lindi
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body 
    #content             
      .container
        .row.justify-content-center
          - flash.each do |key, value| 
            div class="alert alert-#{key}" role="alert" = value
        = yield